---
- name: Prepare epel repo
  hosts: all
  become: true
  roles:
    - geerlingguy.repo-epel

- name: Install Python and pip
  hosts: all
  become: true
  tasks:
    - name: Install Python and pip
      include_role:
        name: geerlingguy.pip
    - name: Create symlink /bin/python -> /bin/python3
      file:
        src: /bin/python3
        dest: /bin/python
        state: link

- name: Install Ansible
  hosts: all
  become: true
  roles:
    - geerlingguy.ansible

- name: Install Docker
  hosts: all
  become: true
  roles:
    - geerlingguy.docker

- name: Install and configure Cockpit
  hosts: all
  become: true
  roles:
    - linux-system-roles.cockpit


- name: Install and configure Nginx to act as a reverse proxy for Cockpit
  hosts: all
  become: true
  roles:
    - nginx
